
target 'NSString+ShellSplit', :exclusive => true do
  pod "NSString+ShellSplit", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'EXPMatchers+FBSnapshotTest'
end
