reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
script:
- xctool test -workspace Example/NSString+ShellSplit.xcworkspace -scheme NSString+ShellSplit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
